### ISSUE TITLE
add /lookup or /l to "commands" section

### ISSUE THREAD

**Issue by samtheman43** [OCNWiki/OCNWiki.github.io#1]
/lookup is a useful command when check a rule-breaker's past infractions.

**Comment by PoseidonsM** [comment]
Added. Pull Request #3 9bd23e8.

**Comment by matic0basle** [comment]
Fixed - https://github.com/OCNWiki/OCNWiki.github.io/commit/847f91876b7c6bc76d62e55ac7c3f5708354d38f
