### ISSUE TITLE
Some minor bugs and additions

### ISSUE THREAD

**Issue by matic0basle** [OCNWiki/OCNWiki.github.io#2]
Trophies page - Each trophy requires a very spcial achievement to be recognised. - Special
To get the internet famous rank you dont need to create overcast network content

Add /modes

**Comment by PoseidonsM** [comment]
Changed internet famous rank description, Added more commands (including /modes and more) and added some new command aliases. Pull Request #3 
57c785d

HAVE NOT EDITTED TROPHIES PAGE FOR THIS ISSUE

**Comment by matic0basle** [comment]
Fixed - https://github.com/OCNWiki/OCNWiki.github.io/commit/847f91876b7c6bc76d62e55ac7c3f5708354d38f
