### ISSUE TITLE
Missing ranks and additions

### ISSUE THREAD

**Issue by stormer1267** [OCNWiki/OCNWiki.github.io#4]
A nice contribution would be to add the discontinued ranks, a few are listed on this threat: https://oc.tc/forums/topics/540b631e67d52297aa00a56d

They include:
Referee: later continued as "ref"
Preppy nazi: https://oc.tc/forums/topics/5085ba19f34422ad7000000a
Donor: before revamp
Severity USA: for the creative server or something like that.
Inactive mod: just got removed
livestreamer: got removed but readded for tournaments (not really a badge anymore).

There are some missing ranks aswell: 
Tournament finalist, tournament winner.
The heart before the donor revamp

Also a suggestion: maybe make a special header for the tournament ranks!

**Comment by matic0basle** [comment]
Tournament winner and finalist arent really ranks are they?

As for discontinued badges, that is planned. The hearts are also planned

**Comment by matic0basle** [comment]
Added in https://github.com/OCNWiki/OCNWiki.github.io/commit/9fc007c2b370cf0dc04379778c6b067f64fc5799
