### ISSUE TITLE
Missing stars/badges and additions

### ISSUE THREAD

**Issue by stormer1267** [OCNWiki/OCNWiki.github.io#5]
Under the staff ranks the stars for the following ranks are missing:
Event coordinator, official and referee

Also the tiny star that is give to the tournament winners that they can pick the color of is missing.

Again the suggestion to add a tournament section.

**Comment by matic0basle** [comment]
The stars are missing because I don't know what colors they are since they were changed a couple of times. As for the tournament winner star that star changes colors and I am not sure which color it is ATM.

If you could give me the colors or if I get them from somewhere I'll add those.

**Comment by stormer1267** [comment]
The referee badge is light grey or grey, (#999999)
The official badge is some sort of dark cyanish, (#19ACAC)
The EC star is the same colour as the player names which is light blue if I am correct. (#00FFFF) 
_I don't know the color codes for sure, I just estimated the colours to what they look like in game._

as to the winner stars, I have to dig into that some more, I will come to you later when I know the answers for sure.

**Comment by matic0basle** [comment]
@stormer1267 Heres the chat colors
https://docs.oc.tc/reference/formatting

**Comment by stormer1267** [comment]
This would make the EC: Aqua (b) 
The offical: Dark_aqua (2)
and the referee: Dark_grey (8)
