### ISSUE TITLE
wrong trophy image "decryption master"

### ISSUE THREAD

**Issue by stormer1267** [OCNWiki/OCNWiki.github.io#6]
the "decryption master" badge image got changed,  it got changed from the lock to the key. as you can see on for example khazhyk's profile (https://oc.tc/khazhyk)

**Comment by PoseidonsM** [comment]
Fixed in pull request #3 
84490e8

**Comment by matic0basle** [comment]
Fixed - https://github.com/OCNWiki/OCNWiki.github.io/commit/847f91876b7c6bc76d62e55ac7c3f5708354d38f
