### ISSUE TITLE
Tournament Winners

### ISSUE THREAD

**Issue by PoseidonsM** [OCNWiki/OCNWiki.github.io#7]
Beta Tournament - Badlion
Attack of the Cores - Starfish
Raiders of the Lost Wool - Starfish
Goblet of Gamemodes - Starfish
Return of the Hill - GM1
Breaking Core - LungGlove
Conquest - Impact
Guardians of the Wool - Impact
House of Cores - Oklahomies

Add a new page to the events section in the wiki: Tournament Winners (with above information)

**Comment by PoseidonsM** [comment]
*Add information to the Past Events page.

**Comment by PoseidonsM** [comment]
Added. 
Pull Request #3 4cd21e7

**Comment by PoseidonsM** [comment]
Will be fixed when more information is gathered.

**Comment by matic0basle** [comment]
Planned and will be done in a different way when I get tournament information

**Comment by mattgu16** [comment]
Consider switching conquest and gotw for the sake of chronological order
